version: '3.8'
services:
  db-service:
    build: ./db-service
    env_file:
      - ./db-service/.env
    ports:
      - "8000:8000"

  api-service:
    build: ./api-service
    env_file:
      - ./api-service/.env
    depends_on:
      - db-service
    ports:
      - "3000:3000"

