version: '3.8'
services:
  db-service:
    build: ./db-service
    env_file:
      - ./db-service/.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  api-service:
    image: your_api_image
    env_file:
      - ./api-service/.env
    depends_on:
      - db-service
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: